server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
    username: postgres.dtrqehgokyldwswyddvs
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ereniridere7@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true	
supabase:
  url: https://dtrqehgokyldwswyddvs.supabase.co
  key: ${SUPABASE_KEY}
  bucket: komsum-images